name: codecore_mobile
description: CodeCore mobile client
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.13.2

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.2
  go_router: ^18.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
